# Pattern File location
PatternFile : PatternFiles/UniformEvent.txt
# SW Reference file location
ReferenceFile : IDontExistYetReference.csv
# Directory for simulation output
DebuggingOutputDir : DebuggingOutput
# Number of events in the file
nEvents : 1
# Length of one event in clock cycles (including gap)
EventLength : 100
# Clock period in nanoseconds
clkPeriod : 2.1
